/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/uZKWznDAl9X
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client'
export default function TestPage() {
  return (
    (<div className="bg-background text-foreground min-h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6">
        <div className="container mx-auto flex justify-between items-center">
          <div className="text-2xl font-bold">경기 결과 분석</div>
          <nav>
            <ul className="flex space-x-4">
              <li>
                <a href="#" className="hover:text-accent">
                  홈
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-accent">
                  분석 보고서
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-accent">
                  리그 순위
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-accent">
                  선수 통계
                </a>
              </li>
            </ul>
          </nav>
        </div>
      </header>
      <main className="container mx-auto py-8 px-4 md:px-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div>
            <h2 className="text-2xl font-bold mb-4 text-center">경기 통계 데이터</h2>
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-card p-4 rounded-lg shadow">
                <h3 className="text-lg font-semibold mb-2">슈팅</h3>
                <div className="flex justify-between">
                  <div>팀 A</div>
                  <div>12</div>
                </div>
                <div className="flex justify-between">
                  <div>팀 B</div>
                  <div>8</div>
                </div>
              </div>
              <div className="bg-card p-4 rounded-lg shadow">
                <h3 className="text-lg font-semibold mb-2">선방</h3>
                <div className="flex justify-between">
                  <div>팀 A</div>
                  <div>5</div>
                </div>
                <div className="flex justify-between">
                  <div>팀 B</div>
                  <div>3</div>
                </div>
              </div>
              <div className="bg-card p-4 rounded-lg shadow">
                <h3 className="text-lg font-semibold mb-2">파울</h3>
                <div className="flex justify-between">
                  <div>팀 A</div>
                  <div>10</div>
                </div>
                <div className="flex justify-between">
                  <div>팀 B</div>
                  <div>8</div>
                </div>
              </div>
              <div className="bg-card p-4 rounded-lg shadow">
                <h3 className="text-lg font-semibold mb-2">코너킥</h3>
                <div className="flex justify-between">
                  <div>팀 A</div>
                  <div>6</div>
                </div>
                <div className="flex justify-between">
                  <div>팀 B</div>
                  <div>4</div>
                </div>
              </div>
              <div className="bg-card p-4 rounded-lg shadow">
                <h3 className="text-lg font-semibold mb-2">오프사이드</h3>
                <div className="flex justify-between">
                  <div>팀 A</div>
                  <div>3</div>
                </div>
                <div className="flex justify-between">
                  <div>팀 B</div>
                  <div>2</div>
                </div>
              </div>
              <div className="bg-card p-4 rounded-lg shadow">
                <h3 className="text-lg font-semibold mb-2">점유율</h3>
                <div className="flex justify-between">
                  <div>팀 A</div>
                  <div>55%</div>
                </div>
                <div className="flex justify-between">
                  <div>팀 B</div>
                  <div>45%</div>
                </div>
              </div>
              <div className="bg-card p-4 rounded-lg shadow">
                <h3 className="text-lg font-semibold mb-2">패스</h3>
                <div className="flex justify-between">
                  <div>팀 A</div>
                  <div>450</div>
                </div>
                <div className="flex justify-between">
                  <div>팀 B</div>
                  <div>380</div>
                </div>
              </div>
            </div>
          </div>
          <div>
            <h2 className="text-2xl font-bold mb-4 text-center">모델링 과정 설명</h2>
            <div className="bg-card p-4 rounded-lg shadow">
              <h3 className="text-lg font-semibold mb-2">피쳐 중요도</h3>
              <div className="grid grid-cols-2 gap-2">
                <div>슈팅</div>
                <div className="font-semibold">0.25</div>
                <div>선방</div>
                <div className="font-semibold">0.20</div>
                <div>파울</div>
                <div className="font-semibold">0.15</div>
                <div>코너킥</div>
                <div className="font-semibold">0.12</div>
                <div>오프사이드</div>
                <div className="font-semibold">0.10</div>
                <div>점유율</div>
                <div className="font-semibold">0.08</div>
                <div>패스</div>
                <div className="font-semibold">0.10</div>
              </div>
            </div>
            <div className="bg-card p-4 rounded-lg shadow mt-4">
              <h3 className="text-lg font-semibold mb-2">분석 방법</h3>
              <p>
                이 분석에서는 경기 통계 데이터를 활용하여 팀의 성과를 비교하고, 각 피쳐의 중요도를 분석하였습니다. 이를
                통해 어떤 요인들이 경기 결과에 더 큰 영향을 미쳤는지 파악할 수 있습니다.
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>)
  );
}
