/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2EiUkiJrrQA
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'
import { Archivo } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client'
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"

export default function TestPage() {
  return (
    (<div className="grid gap-8">
      <section>
        <h2 className="text-2xl font-bold mb-4">이번 주 경기</h2>
        <div className="grid md:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <CardTitle>FC 서울 vs 수원 삼성 블루윙즈</CardTitle>
              <CardDescription>2024년 6월 21일 | 오후 7시 30분</CardDescription>
            </CardHeader>
            <CardContent className="grid gap-2">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    alt="FC 서울"
                    width={32}
                    height={32}
                    className="rounded-full"
                    style={{ aspectRatio: "32/32", objectFit: "cover" }} />
                  <span>FC 서울</span>
                </div>
                <div className="text-2xl font-bold">2</div>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    alt="수원 삼성 블루윙즈"
                    width={32}
                    height={32}
                    className="rounded-full"
                    style={{ aspectRatio: "32/32", objectFit: "cover" }} />
                  <span>수원 삼성 블루윙즈</span>
                </div>
                <div className="text-2xl font-bold">1</div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>울산 현대 vs 전북 현대 모터스</CardTitle>
              <CardDescription>2024년 6월 22일 | 오후 5시</CardDescription>
            </CardHeader>
            <CardContent className="grid gap-2">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    alt="울산 현대"
                    width={32}
                    height={32}
                    className="rounded-full"
                    style={{ aspectRatio: "32/32", objectFit: "cover" }} />
                  <span>울산 현대</span>
                </div>
                <div className="text-2xl font-bold">1</div>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    alt="전북 현대 모터스"
                    width={32}
                    height={32}
                    className="rounded-full"
                    style={{ aspectRatio: "32/32", objectFit: "cover" }} />
                  <span>전북 현대 모터스</span>
                </div>
                <div className="text-2xl font-bold">0</div>
              </div>
            </CardContent>
          </Card>
        </div>
      </section>
      <section>
        <h2 className="text-2xl font-bold mb-4">지난 경기</h2>
        <div className="grid gap-4">
          <Card>
            <CardHeader>
              <CardTitle>수원 삼성 블루윙즈 vs 울산 현대</CardTitle>
              <CardDescription>2024년 6월 18일 | 오후 7시 30분</CardDescription>
            </CardHeader>
            <CardContent className="grid gap-2">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    alt="수원 삼성 블루윙즈"
                    width={32}
                    height={32}
                    className="rounded-full"
                    style={{ aspectRatio: "32/32", objectFit: "cover" }} />
                  <span>수원 삼성 블루윙즈</span>
                </div>
                <div className="text-2xl font-bold">2</div>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    alt="울산 현대"
                    width={32}
                    height={32}
                    className="rounded-full"
                    style={{ aspectRatio: "32/32", objectFit: "cover" }} />
                  <span>울산 현대</span>
                </div>
                <div className="text-2xl font-bold">1</div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>전북 현대 모터스 vs FC 서울</CardTitle>
              <CardDescription>2024년 6월 15일 | 오후 5시</CardDescription>
            </CardHeader>
            <CardContent className="grid gap-2">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    alt="전북 현대 모터스"
                    width={32}
                    height={32}
                    className="rounded-full"
                    style={{ aspectRatio: "32/32", objectFit: "cover" }} />
                  <span>전북 현대 모터스</span>
                </div>
                <div className="text-2xl font-bold">3</div>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    alt="FC 서울"
                    width={32}
                    height={32}
                    className="rounded-full"
                    style={{ aspectRatio: "32/32", objectFit: "cover" }} />
                  <span>FC 서울</span>
                </div>
                <div className="text-2xl font-bold">1</div>
              </div>
            </CardContent>
          </Card>
        </div>
      </section>
      <section>
        <h2 className="text-2xl font-bold mb-4">팀 순위</h2>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>순위</TableHead>
              <TableHead>팀</TableHead>
              <TableHead>경기</TableHead>
              <TableHead>승</TableHead>
              <TableHead>무</TableHead>
              <TableHead>패</TableHead>
              <TableHead>득점</TableHead>
              <TableHead>실점</TableHead>
              <TableHead>득실차</TableHead>
              <TableHead>승점</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell>1</TableCell>
              <TableCell>
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    alt="울산 현대"
                    width={24}
                    height={24}
                    className="rounded-full"
                    style={{ aspectRatio: "24/24", objectFit: "cover" }} />
                  <span>울산 현대</span>
                </div>
              </TableCell>
              <TableCell>15</TableCell>
              <TableCell>12</TableCell>
              <TableCell>2</TableCell>
              <TableCell>1</TableCell>
              <TableCell>32</TableCell>
              <TableCell>12</TableCell>
              <TableCell>20</TableCell>
              <TableCell>38</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>2</TableCell>
              <TableCell>
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    alt="전북 현대 모터스"
                    width={24}
                    height={24}
                    className="rounded-full"
                    style={{ aspectRatio: "24/24", objectFit: "cover" }} />
                  <span>전북 현대 모터스</span>
                </div>
              </TableCell>
              <TableCell>15</TableCell>
              <TableCell>10</TableCell>
              <TableCell>3</TableCell>
              <TableCell>2</TableCell>
              <TableCell>28</TableCell>
              <TableCell>15</TableCell>
              <TableCell>13</TableCell>
              <TableCell>33</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>3</TableCell>
              <TableCell>
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    alt="FC 서울"
                    width={24}
                    height={24}
                    className="rounded-full"
                    style={{ aspectRatio: "24/24", objectFit: "cover" }} />
                  <span>FC 서울</span>
                </div>
              </TableCell>
              <TableCell>15</TableCell>
              <TableCell>8</TableCell>
              <TableCell>5</TableCell>
              <TableCell>2</TableCell>
              <TableCell>24</TableCell>
              <TableCell>18</TableCell>
              <TableCell>6</TableCell>
              <TableCell>29</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>4</TableCell>
              <TableCell>
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    alt="수원 삼성 블루윙즈"
                    width={24}
                    height={24}
                    className="rounded-full"
                    style={{ aspectRatio: "24/24", objectFit: "cover" }} />
                  <span>수원 삼성 블루윙즈</span>
                </div>
              </TableCell>
              <TableCell>15</TableCell>
              <TableCell>7</TableCell>
              <TableCell>4</TableCell>
              <TableCell>4</TableCell>
              <TableCell>22</TableCell>
              <TableCell>20</TableCell>
              <TableCell>2</TableCell>
              <TableCell>25</TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </section>
      <section>
        <h2 className="text-2xl font-bold mb-4">선수 순위</h2>
        <div className="grid md:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <CardTitle>득점왕</CardTitle>
            </CardHeader>
            <CardContent className="grid gap-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    alt="선수 1"
                    width={32}
                    height={32}
                    className="rounded-full"
                    style={{ aspectRatio: "32/32", objectFit: "cover" }} />
                  <span>조규성</span>
                </div>
                <div className="text-lg font-bold">12 골</div>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    alt="선수 2"
                    width={32}
                    height={32}
                    className="rounded-full"
                    style={{ aspectRatio: "32/32", objectFit: "cover" }} />
                  <span>구스타보</span>
                </div>
                <div className="text-lg font-bold">10 골</div>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    alt="선수 3"
                    width={32}
                    height={32}
                    className="rounded-full"
                    style={{ aspectRatio: "32/32", objectFit: "cover" }} />
                  <span>김신욱</span>
                </div>
                <div className="text-lg font-bold">9 골</div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>도움왕</CardTitle>
            </CardHeader>
            <CardContent className="grid gap-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    alt="선수 4"
                    width={32}
                    height={32}
                    className="rounded-full"
                    style={{ aspectRatio: "32/32", objectFit: "cover" }} />
                  <span>이재성</span>
                </div>
                <div className="text-lg font-bold">8 도움</div>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    alt="선수 5"
                    width={32}
                    height={32}
                    className="rounded-full"
                    style={{ aspectRatio: "32/32", objectFit: "cover" }} />
                  <span>한교원</span>
                </div>
                <div className="text-lg font-bold">7 도움</div>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    alt="선수 6"
                    width={32}
                    height={32}
                    className="rounded-full"
                    style={{ aspectRatio: "32/32", objectFit: "cover" }} />
                  <span>윤빛가람</span>
                </div>
                <div className="text-lg font-bold">6 도움</div>
              </div>
            </CardContent>
          </Card>
        </div>
      </section>
    </div>)
  );
}
