/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/DbzJ82pYyip
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { DM_Serif_Display } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

dm_serif_display({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client'
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export default function TestPage() {
  return (
    (<div className="flex flex-col min-h-screen bg-muted/40">
      <header
        className="sticky top-0 z-30 flex h-14 items-center gap-4 border-b bg-background px-4 sm:static sm:h-auto sm:border-0 sm:bg-transparent sm:px-6">
        <Link
          href="#"
          className="flex items-center gap-2 font-semibold"
          prefetch={false}>
          <Package2Icon className="h-6 w-6" />
          <span>커뮤니티 허브</span>
        </Link>
        <nav className="hidden lg:flex items-center gap-4">
          <Link
            href="#"
            className="px-3 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
            prefetch={false}>
            뉴스
          </Link>
          <Link
            href="#"
            className="px-3 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
            prefetch={false}>
            칼럼 및 분석
          </Link>
          <Link
            href="#"
            className="px-3 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
            prefetch={false}>
            승률 예측
          </Link>
          <Link
            href="#"
            className="px-3 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
            prefetch={false}>
            협업 이벤트
          </Link>
        </nav>
        <div className="relative ml-auto flex-1 md:grow-0">
          <div className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
          <Input
            type="search"
            placeholder="검색..."
            className="w-full rounded-lg bg-background pl-8 md:w-[200px] lg:w-[336px]" />
        </div>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline" size="icon" className="overflow-hidden rounded-full">
              <img
                src="/placeholder.svg"
                width={36}
                height={36}
                alt="Avatar"
                className="overflow-hidden rounded-full"
                style={{ aspectRatio: "36/36", objectFit: "cover" }} />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuLabel>내 계정</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem>설정</DropdownMenuItem>
            <DropdownMenuItem>지원</DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem>로그아웃</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </header>
      <main className="flex-1 grid gap-4 p-4 sm:px-6 sm:py-0 md:gap-8">
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
          <Card>
            <CardHeader>
              <CardTitle>최신 뉴스</CardTitle>
              <CardDescription>최신 업계 뉴스를 확인하세요.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <Link href="#" className="flex items-center gap-4" prefetch={false}>
                  <img
                    src="/placeholder.svg"
                    width={80}
                    height={80}
                    alt="뉴스 썸네일"
                    className="rounded-lg object-cover"
                    style={{ aspectRatio: "80/80", objectFit: "cover" }} />
                  <div>
                    <div className="font-medium">새로운 투자 라운드 발표</div>
                    <div className="text-sm text-muted-foreground">
                      우리 회사가 1000만 달러의 시리즈 A 투자를 확보했습니다.
                    </div>
                  </div>
                </Link>
                <Link href="#" className="flex items-center gap-4" prefetch={false}>
                  <img
                    src="/placeholder.svg"
                    width={80}
                    height={80}
                    alt="뉴스 썸네일"
                    className="rounded-lg object-cover"
                    style={{ aspectRatio: "80/80", objectFit: "cover" }} />
                  <div>
                    <div className="font-medium">업계 동향 보고서 발표</div>
                    <div className="text-sm text-muted-foreground">최신 업계 동향 보고서를 다운로드할 수 있습니다.</div>
                  </div>
                </Link>
                <Link href="#" className="flex items-center gap-4" prefetch={false}>
                  <img
                    src="/placeholder.svg"
                    width={80}
                    height={80}
                    alt="뉴스 썸네일"
                    className="rounded-lg object-cover"
                    style={{ aspectRatio: "80/80", objectFit: "cover" }} />
                  <div>
                    <div className="font-medium">새로운 제품 출시</div>
                    <div className="text-sm text-muted-foreground">우리의 최신 제품 출시를 기쁘게 알립니다.</div>
                  </div>
                </Link>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>칼럼 및 분석</CardTitle>
              <CardDescription>심도 있는 기사와 업계 통찰력을 확인하세요.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <Link href="#" className="flex items-center gap-4" prefetch={false}>
                  <img
                    src="/placeholder.svg"
                    width={80}
                    height={80}
                    alt="칼럼 썸네일"
                    className="rounded-lg object-cover"
                    style={{ aspectRatio: "80/80", objectFit: "cover" }} />
                  <div>
                    <div className="font-medium">원격 근무의 미래</div>
                    <div className="text-sm text-muted-foreground">
                      원격 근무로의 전환이 가져올 장기적인 영향을 탐구합니다.
                    </div>
                  </div>
                </Link>
                <Link href="#" className="flex items-center gap-4" prefetch={false}>
                  <img
                    src="/placeholder.svg"
                    width={80}
                    height={80}
                    alt="칼럼 썸네일"
                    className="rounded-lg object-cover"
                    style={{ aspectRatio: "80/80", objectFit: "cover" }} />
                  <div>
                    <div className="font-medium">기술 산업의 지속 가능성</div>
                    <div className="text-sm text-muted-foreground">
                      기술의 환경적 영향과 잠재적 해결책을 살펴봅니다.
                    </div>
                  </div>
                </Link>
                <Link href="#" className="flex items-center gap-4" prefetch={false}>
                  <img
                    src="/placeholder.svg"
                    width={80}
                    height={80}
                    alt="칼럼 썸네일"
                    className="rounded-lg object-cover"
                    style={{ aspectRatio: "80/80", objectFit: "cover" }} />
                  <div>
                    <div className="font-medium">비즈니스에서의 AI 부상</div>
                    <div className="text-sm text-muted-foreground">인공 지능의 변혁적 잠재력을 탐구합니다.</div>
                  </div>
                </Link>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>승률 예측</CardTitle>
              <CardDescription>승률 예측 모델에 대해 논의하고 분석합니다.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <Link href="#" className="flex items-center gap-4" prefetch={false}>
                  <img
                    src="/placeholder.svg"
                    width={80}
                    height={80}
                    alt="예측 모델 썸네일"
                    className="rounded-lg object-cover"
                    style={{ aspectRatio: "80/80", objectFit: "cover" }} />
                  <div>
                    <div className="font-medium">승률 예측을 위한 기계 학습 모델</div>
                    <div className="text-sm text-muted-foreground">
                      기계 학습을 활용한 최신 승률 예측 기술에 대해 논의합니다.
                    </div>
                  </div>
                </Link>
                <Link href="#" className="flex items-center gap-4" prefetch={false}>
                  <img
                    src="/placeholder.svg"
                    width={80}
                    height={80}
                    alt="예측 모델 썸네일"
                    className="rounded-lg object-cover"
                    style={{ aspectRatio: "80/80", objectFit: "cover" }} />
                  <div>
                    <div className="font-medium">베이지안 접근법을 통한 승률 예측</div>
                    <div className="text-sm text-muted-foreground">
                      더 정확한 승률 예측을 위한 베이지안 방법론을 탐구합니다.
                    </div>
                  </div>
                </Link>
                <Link href="#" className="flex items-center gap-4" prefetch={false}>
                  <img
                    src="/placeholder.svg"
                    width={80}
                    height={80}
                    alt="예측 모델 썸네일"
                    className="rounded-lg object-cover"
                    style={{ aspectRatio: "80/80", objectFit: "cover" }} />
                  <div>
                    <div className="font-medium">승률 예측을 위한 앙상블 모델링</div>
                    <div className="text-sm text-muted-foreground">
                      앙상블 방법을 활용하여 승률 예측 정확도를 높이는 방법을 논의합니다.
                    </div>
                  </div>
                </Link>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>협업 이벤트</CardTitle>
              <CardDescription>업계 협업을 위한 다가오는 이벤트를 확인하세요.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <Link href="#" className="flex items-center gap-4" prefetch={false}>
                  <img
                    src="/placeholder.svg"
                    width={80}
                    height={80}
                    alt="이벤트 썸네일"
                    className="rounded-lg object-cover"
                    style={{ aspectRatio: "80/80", objectFit: "cover" }} />
                  <div>
                    <div className="font-medium">기술 산업 네트워킹 이벤트</div>
                    <div className="text-sm text-muted-foreground">
                      업계 전문가들과 네트워킹할 수 있는 이벤트에 참여하세요.
                    </div>
                  </div>
                </Link>
                <Link href="#" className="flex items-center gap-4" prefetch={false}>
                  <img
                    src="/placeholder.svg"
                    width={80}
                    height={80}
                    alt="이벤트 썸네일"
                    className="rounded-lg object-cover"
                    style={{ aspectRatio: "80/80", objectFit: "cover" }} />
                  <div>
                    <div className="font-medium">스타트업 피칭 대회</div>
                    <div className="text-sm text-muted-foreground">
                      귀사의 스타트업을 소개하고 투자 기회를 얻으세요.
                    </div>
                  </div>
                </Link>
                <Link href="#" className="flex items-center gap-4" prefetch={false}>
                  <img
                    src="/placeholder.svg"
                    width={80}
                    height={80}
                    alt="이벤트 썸네일"
                    className="rounded-lg object-cover"
                    style={{ aspectRatio: "80/80", objectFit: "cover" }} />
                  <div>
                    <div className="font-medium">업계 혁신 정상회의</div>
                    <div className="text-sm text-muted-foreground">기술 산업의 최신 동향과 혁신을 탐구하세요.</div>
                  </div>
                </Link>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="grid gap-4">
          <Card>
            <CardHeader>
              <CardTitle>최신 댓글</CardTitle>
              <CardDescription>토론에 참여하고 의견을 공유하세요.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <div className="flex items-start gap-4">
                  <Avatar className="w-8 h-8 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="사용자 아바타" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div>
                    <div className="font-medium">John Doe</div>
                    <div className="text-sm text-muted-foreground">
                      훌륭한 기사였습니다! 원격 근무의 미래에 대한 통찰력이 인상 깊었습니다.
                    </div>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <Avatar className="w-8 h-8 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="사용자 아바타" />
                    <AvatarFallback>SA</AvatarFallback>
                  </Avatar>
                  <div>
                    <div className="font-medium">Sarah Anderson</div>
                    <div className="text-sm text-muted-foreground">
                      베이지안 접근법을 통한 승률 예측에 대한 논의가 흥미롭습니다. 더 자세히 알아보고 싶습니다.
                    </div>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <Avatar className="w-8 h-8 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="사용자 아바타" />
                    <AvatarFallback>MJ</AvatarFallback>
                  </Avatar>
                  <div>
                    <div className="font-medium">Michael Johnson</div>
                    <div className="text-sm text-muted-foreground">
                      기술 산업 네트워킹 이벤트에 참석하기를 기대하고 있습니다. 다른 전문가들과 교류할 수 있는 좋은 기회
                      같습니다.
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
      <footer className="bg-muted/40 py-6 px-4 sm:px-6">
        <div className="container mx-auto flex items-center justify-between">
          <div className="text-sm text-muted-foreground">&copy; 2023</div>
        </div>
      </footer>
    </div>)
  );
}

function Package2Icon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>)
  );
}
