/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/dZIcpcN4IB8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Crimson_Text } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

crimson_text({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client'
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { CartesianGrid, XAxis, Line, LineChart, Area, AreaChart } from "recharts"
import { ChartTooltipContent, ChartTooltip, ChartContainer } from "@/components/ui/chart"

export default function test01() {
  return (
    (<div className="flex flex-col min-h-screen">
      <header
        className="bg-primary text-primary-foreground py-4 px-6 md:px-8 lg:px-10 shadow-md">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#" className="text-xl font-bold" prefetch={false}>
            K리그
          </Link>
          <nav className="hidden md:flex items-center space-x-6">
            <Link href="/test02" className="hover:underline" prefetch={false}>
              프로젝트 소개
            </Link>
            <Link href="/test03" className="hover:underline" prefetch={false}>
              경기 기록
            </Link>
            <Link href="/test04" className="hover:underline" prefetch={false}>
              경기 분석
            </Link>
            <Link href="/test05" className="hover:underline" prefetch={false}>
              팀 전략
            </Link>
            <Link href="/test06" className="hover:underline" prefetch={false}>
              커뮤니티
            </Link>
          </nav>
          <Button variant="outline" className="md:hidden">
            <MenuIcon className="h-6 w-6" />
            <span className="sr-only">메뉴 토글</span>
          </Button>
        </div>
      </header>
      <main className="flex-1">
        <section id="introduction" className="py-12 md:py-16 lg:py-20">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <div className="grid md:grid-cols-2 gap-8">
              <div>
                <h2 className="text-3xl font-bold mb-4">K리그에 오신 것을 환영합니다</h2>
                <p className="text-muted-foreground mb-6">
                  K리그는 대한민국 최고의 프로축구 리그로, 국내 최고의 팀과 선수들이 출전합니다. 풍부한 역사와 열정적인
                  팬들로 인해 K리그는 세계적인 축구 무대로 자리잡았습니다.
                </p>
                <p className="text-muted-foreground mb-6">
                  리그의 인기는 또한 활발한 스포츠 베팅 산업을 이끌어 왔으며, 팬들과 애호가들은 경기와 팀에 대한 정보를
                  면밀히 분석하여 현명한 베팅을 하고 있습니다.
                </p>
              </div>
              <div>
                <img
                  src="/placeholder.svg"
                  width={600}
                  height={400}
                  alt="K리그 경기"
                  className="rounded-lg object-cover"
                  style={{ aspectRatio: "600/400", objectFit: "cover" }} />
              </div>
            </div>
          </div>
        </section>
        <section id="match-records" className="py-12 md:py-16 lg:py-20 bg-muted">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <h2 className="text-3xl font-bold mb-8">경기 기록</h2>
            <div className="grid md:grid-cols-2 gap-8">
              <div>
                <p className="text-muted-foreground mb-6">
                  경기 기록 섹션에서는 과거와 향후 K리그 경기에 대한 자세한 정보를 확인할 수 있습니다. 여기에는 팀
                  라인업, 득점자, 경기 통계 등이 포함됩니다.
                </p>
                <p className="text-muted-foreground mb-6">
                  우리의 포괄적인 데이터베이스를 통해 리그의 역사를 깊이 있게 탐구할 수 있으며, 이를 바탕으로 스포츠
                  베팅에 대한 현명한 결정을 내릴 수 있습니다.
                </p>
              </div>
              <div>
                <Card>
                  <CardHeader>
                    <CardTitle>경기 세부 정보</CardTitle>
                    <CardDescription>전북 현대 모터스 vs 울산 현대</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <h3 className="text-lg font-bold mb-2">전북 현대</h3>
                        <div className="flex items-center space-x-2">
                          <img
                            src="/placeholder.svg"
                            width={40}
                            height={40}
                            alt="전북 현대"
                            className="rounded-full"
                            style={{ aspectRatio: "40/40", objectFit: "cover" }} />
                          <span>2</span>
                        </div>
                      </div>
                      <div>
                        <h3 className="text-lg font-bold mb-2">울산 현대</h3>
                        <div className="flex items-center space-x-2">
                          <img
                            src="/placeholder.svg"
                            width={40}
                            height={40}
                            alt="울산 현대"
                            className="rounded-full"
                            style={{ aspectRatio: "40/40", objectFit: "cover" }} />
                          <span>1</span>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                  <CardFooter>
                    <div className="flex items-center justify-between">
                      <span className="text-muted-foreground">2023년 5월 1일 - 오후 7시 30분</span>
                      <span className="text-muted-foreground">전주월드컵경기장</span>
                    </div>
                  </CardFooter>
                </Card>
              </div>
            </div>
          </div>
        </section>
        <section id="match-analysis" className="py-12 md:py-16 lg:py-20">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <h2 className="text-3xl font-bold mb-8">경기 결과 분석</h2>
            <div className="grid md:grid-cols-2 gap-8">
              <div>
                <p className="text-muted-foreground mb-6">
                  경기 결과 분석 섹션에서는 K리그 경기 결과에 대한 심층적인 통찰과 동향을 탐색할 수 있습니다. 우리
                  전문가 팀은 팀 성과, 선수 통계, 역사적 데이터 등 다양한 요인을 분석하여 귀중한 정보를 제공합니다.
                </p>
                <p className="text-muted-foreground mb-6">
                  경험 많은 스포츠 베터든 일반 팬이든 이 섹션을 통해 K리그의 역학을 더 잘 이해하고 더 현명한 결정을 내릴
                  수 있습니다.
                </p>
              </div>
              <div>
                <LinechartChart className="aspect-[16/9]" />
              </div>
            </div>
          </div>
        </section>
        <section id="team-strategy" className="py-12 md:py-16 lg:py-20 bg-muted">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <h2 className="text-3xl font-bold mb-8">팀 전략 분석</h2>
            <div className="grid md:grid-cols-2 gap-8">
              <div>
                <p className="text-muted-foreground mb-6">
                  팀 전략 분석 섹션에서는 다양한 K리그 팀들이 사용하는 독특한 접근법과 전술을 살펴볼 수 있습니다. 우리
                  전문가들은 각 팀의 플레이 스타일, 강점, 약점 등을 심도 있게 분석합니다.
                </p>
                <p className="text-muted-foreground mb-6">
                  K리그 팀들의 전략적 미묘함을 이해하면 스포츠 베팅에서 경쟁력 있는 우위를 점할 수 있습니다. 이를 통해
                  더 정확한 예측과 베팅을 할 수 있습니다.
                </p>
              </div>
              <div>
                <AreachartChart className="aspect-[16/9]" />
              </div>
            </div>
          </div>
        </section>
        <section id="community" className="py-12 md:py-16 lg:py-20">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <h2 className="text-3xl font-bold mb-8">K리그 커뮤니티에 참여하세요</h2>
            <div className="grid md:grid-cols-2 gap-8">
              <div>
                <p className="text-muted-foreground mb-6">
                  K리그 웹사이트에는 팬, 전문가, 스포츠 애호가들이 참여하는 활발한 커뮤니티가 있습니다. 여기서 사람들은
                  토론, 통찰 공유, 동료 팬들과의 교류 등을 할 수 있습니다.
                </p>
                <p className="text-muted-foreground mb-6">
                  최신 경기 결과 논의, 팀 전략 분석, 그리고 단순히 다른 K리그 팬들과 교류하고 싶다면 우리 커뮤니티
                  플랫폼이 그 공간을 제공합니다.
                </p>
              </div>
              <div>
                <Card>
                  <CardHeader>
                    <CardTitle>최신 커뮤니티 토론</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-4">
                      <div className="flex items-start space-x-4">
                        <Avatar className="w-8 h-8">
                          <AvatarImage src="/placeholder-user.jpg" alt="사용자 아바타" />
                          <AvatarFallback>JD</AvatarFallback>
                        </Avatar>
                        <div>
                          <h4 className="font-medium">전북 현대의 수비 전술</h4>
                          <p className="text-muted-foreground">
                            &quot;전북의 4-2-3-1 포메이션이 상대 공격을 효과적으로 차단하고 있다고 생각합니다...&quot;
                          </p>
                        </div>
                      </div>
                      <div className="flex items-start space-x-4">
                        <Avatar className="w-8 h-8">
                          <AvatarImage src="/placeholder-user.jpg" alt="사용자 아바타" />
                          <AvatarFallback>SK</AvatarFallback>
                        </Avatar>
                        <div>
                          <h4 className="font-medium">다가오는 K리그 시즌 예측</h4>
                          <p className="text-muted-foreground">
                            &quot;새로운 영입과 감독 변경으로 인해 울산 현대가 이번 시즌 최강팀이 될 것
                            같습니다...&quot;
                          </p>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                  <CardFooter>
                    <Link
                      href="#"
                      className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                      prefetch={false}>
                      토론에 참여하기
                    </Link>
                  </CardFooter>
                </Card>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-primary text-primary-foreground py-6 px-4 md:px-6 lg:px-8">
        <div className="container mx-auto flex items-center justify-between">
          <p className="text-sm">&copy; 2024 K리그. All rights reserved.</p>
          <nav className="flex items-center space-x-4">
            <Link href="#" className="hover:underline" prefetch={false}>
              이용 약관
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              개인정보 정책
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              문의하기
            </Link>
          </nav>
        </div>
      </footer>
    </div>)
  );
}

function AreachartChart(props) {
  return (
    (<div {...props}>
      <ChartContainer
        config={{
          desktop: {
            label: "Desktop",
            color: "hsl(var(--chart-1))",
          },
        }}
        className="min-h-[300px]">
        <AreaChart
          accessibilityLayer
          data={[
            { month: "January", desktop: 186 },
            { month: "February", desktop: 305 },
            { month: "March", desktop: 237 },
            { month: "April", desktop: 73 },
            { month: "May", desktop: 209 },
            { month: "June", desktop: 214 },
          ]}
          margin={{
            left: 12,
            right: 12,
          }}>
          <CartesianGrid vertical={false} />
          <XAxis
            dataKey="month"
            tickLine={false}
            axisLine={false}
            tickMargin={8}
            tickFormatter={(value) => value.slice(0, 3)} />
          <ChartTooltip cursor={false} content={<ChartTooltipContent indicator="line" />} />
          <Area
            dataKey="desktop"
            type="natural"
            fill="var(--color-desktop)"
            fillOpacity={0.4}
            stroke="var(--color-desktop)" />
        </AreaChart>
      </ChartContainer>
    </div>)
  );
}


function LinechartChart(props) {
  return (
    (<div {...props}>
      <ChartContainer
        config={{
          desktop: {
            label: "Desktop",
            color: "hsl(var(--chart-1))",
          },
        }}>
        <LineChart
          accessibilityLayer
          data={[
            { month: "January", desktop: 186 },
            { month: "February", desktop: 305 },
            { month: "March", desktop: 237 },
            { month: "April", desktop: 73 },
            { month: "May", desktop: 209 },
            { month: "June", desktop: 214 },
          ]}
          margin={{
            left: 12,
            right: 12,
          }}>
          <CartesianGrid vertical={false} />
          <XAxis
            dataKey="month"
            tickLine={false}
            axisLine={false}
            tickMargin={8}
            tickFormatter={(value) => value.slice(0, 3)} />
          <ChartTooltip cursor={false} content={<ChartTooltipContent hideLabel />} />
          <Line
            dataKey="desktop"
            type="natural"
            stroke="var(--color-desktop)"
            strokeWidth={2}
            dot={false} />
        </LineChart>
      </ChartContainer>
    </div>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}
