/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/dQzCGh9Lyge
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client'
import Link from "next/link"
import { Button } from "@/components/ui/button"

export default function TestPage() {
  return (
    (<div className="bg-background text-foreground">
      <header className="py-6 px-4 md:px-6 flex items-center justify-between border-b">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <ClubIcon className="w-8 h-8" />
          <span className="text-xl font-bold">K리그</span>
        </Link>
        <nav className="hidden md:flex items-center gap-4">
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            홈
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            팀
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            선수
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            뉴스
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            소개
          </Link>
        </nav>
        <Button variant="outline" size="icon" className="md:hidden">
          <MenuIcon className="w-6 h-6" />
          <span className="sr-only">메뉴 열기</span>
        </Button>
      </header>
      <main>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-8 lg:grid-cols-2 lg:items-center">
              <div className="space-y-4">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">K리그 프로젝트 소개</h1>
                <p className="text-muted-foreground md:text-xl/relaxed">
                  한국 프로축구 리그인 K리그의 데이터와 통찰력을 탐험해보세요. 이 매력적인 리그의 본질을 발견하고
                  이해해보세요.
                </p>
              </div>
              <div className="grid gap-4">
                <img
                  src="/placeholder.svg"
                  width={600}
                  height={400}
                  alt="K리그"
                  className="rounded-lg"
                  style={{ aspectRatio: "600/400", objectFit: "cover" }} />
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="grid gap-8 lg:grid-cols-2 lg:items-center">
              <div className="grid gap-4">
                <img
                  src="/placeholder.svg"
                  width={600}
                  height={400}
                  alt="K리그 데이터"
                  className="rounded-lg"
                  style={{ aspectRatio: "600/400", objectFit: "cover" }} />
              </div>
              <div className="space-y-4">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">K리그 데이터 탐험</h2>
                <p className="text-muted-foreground md:text-xl/relaxed">
                  우리의 K리그 프로젝트는 리그의 풍부한 데이터를 깊이 있게 탐구하여 팀과 선수들의 성과, 전술, 트렌드에
                  대한 통찰력 있는 정보를 제공합니다.
                </p>
                <div className="grid gap-4">
                  <div>
                    <h3 className="text-xl font-bold">종합적인 데이터</h3>
                    <p className="text-muted-foreground">
                      선수 통계, 팀 성과 지표, 역사적 경기 데이터 등 다양한 데이터 포인트를 수집하여 리그에 대한
                      전체적인 관점을 제공합니다.
                    </p>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold">심화 분석</h3>
                    <p className="text-muted-foreground">
                      우리의 프로젝트는 숨겨진 패턴을 발견하고, 핵심 요인을 식별하며, 통찰력 있는 시각화를 생성하는 등의
                      고급 분석 기술을 활용합니다.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-8 lg:grid-cols-2 lg:items-center">
              <div className="space-y-4">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">K리그의 본질 발견</h2>
                <p className="text-muted-foreground md:text-xl/relaxed">
                  우리의 K리그 프로젝트는 단순한 데이터 분석을 넘어서, 이 매력적인 리그의 진정한 본질을 포착하고자
                  합니다. 경기장에서 펼쳐지는 감동적인 이야기와 독특한 특성을 조명할 것입니다.
                </p>
                <div className="grid gap-4">
                  <div>
                    <h3 className="text-xl font-bold">스토리텔링</h3>
                    <p className="text-muted-foreground">
                      우리의 프로젝트를 통해 선수들의 승리와 고난, 그리고 개성 있는 인물들이 만들어내는 감동적인
                      이야기를 전할 것입니다.
                    </p>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold">독특한 통찰</h3>
                    <p className="text-muted-foreground">
                      심도 있는 분석을 통해 K리그만의 독특한 특성과 트렌드를 발견하고, 팬들과 애호가들에게 깊이 있는
                      이해를 제공할 것입니다.
                    </p>
                  </div>
                </div>
              </div>
              <div className="grid gap-4">
                <img
                  src="/placeholder.svg"
                  width={600}
                  height={400}
                  alt="K리그의 본질"
                  className="rounded-lg"
                  style={{ aspectRatio: "600/400", objectFit: "cover" }} />
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted py-6 px-4 md:px-6 border-t">
        <div className="container flex items-center justify-between">
          <p className="text-sm text-muted-foreground">&copy; 2024 K리그. All rights reserved.</p>
          <div className="flex items-center gap-4">
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              개인정보 보호
            </Link>
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              이용 약관
            </Link>
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              문의하기
            </Link>
          </div>
        </div>
      </footer>
    </div>)
  );
}

function ClubIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M17.28 9.05a5.5 5.5 0 1 0-10.56 0A5.5 5.5 0 1 0 12 17.66a5.5 5.5 0 1 0 5.28-8.6Z" />
      <path d="M12 17.66L12 22" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}
